# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: false

cache:
  packages: true

warnings_are_errors: true

r_packages:
  - covr

r_github_packages:
  - rstudio/shinytest

after_success:
  - Rscript -e 'covr::codecov()'
